server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000 # This is not required
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
#    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
