/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : local
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : PERSONPAPER

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-07-17 17:48:38
*/


-- ----------------------------
-- Table structure for ATTACHMENT
-- ----------------------------
DROP TABLE "PERSONPAPER"."ATTACHMENT";
CREATE TABLE "PERSONPAPER"."ATTACHMENT" (
"ID" NUMBER(10) NOT NULL ,
"AMPUTATED" NUMBER(10) NULL ,
"ATTACHMENT_SIZE" NUMBER(10) NOT NULL ,
"CREATED_DATE_TIME" TIMESTAMP(6)  NULL ,
"CREATED_USER_ID" NUMBER(10) NULL ,
"CREATED_USER_NAME" VARCHAR2(55 CHAR) NULL ,
"FILE_NAME" VARCHAR2(105 CHAR) NOT NULL ,
"LAST_UPDATE_DATE_TIME" TIMESTAMP(6)  NULL ,
"LAST_UPDATE_USER_ID" NUMBER(10) NULL ,
"LAST_UPDATE_USER_NAME" VARCHAR2(55 CHAR) NULL ,
"RESOURCES_ID" NUMBER(10) NOT NULL ,
"RESOURCES_TYPE" NUMBER(10) NOT NULL ,
"SOURCE_FILE_NAME" VARCHAR2(105 CHAR) NOT NULL ,
"SUFFIX" VARCHAR2(10 CHAR) NOT NULL ,
"TAG" VARCHAR2(105 CHAR) NULL ,
"URL" VARCHAR2(255 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ATTACHMENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table ATTACHMENT
-- ----------------------------
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("ATTACHMENT_SIZE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("FILE_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("RESOURCES_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("RESOURCES_TYPE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("SOURCE_FILE_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("SUFFIX" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("URL" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("ATTACHMENT_SIZE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("FILE_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("RESOURCES_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("RESOURCES_TYPE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("SOURCE_FILE_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("SUFFIX" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ATTACHMENT" ADD CHECK ("URL" IS NOT NULL);
