/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : local
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : PERSONPAPER

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-07-17 17:50:14
*/


-- ----------------------------
-- Table structure for MENU
-- ----------------------------
DROP TABLE "PERSONPAPER"."MENU";
CREATE TABLE "PERSONPAPER"."MENU" (
"ID" NUMBER(10) NOT NULL ,
"CODE" VARCHAR2(255 CHAR) NOT NULL ,
"CREATED_DATE_TIME" TIMESTAMP(6)  NOT NULL ,
"CREATED_USER_ID" NUMBER(10) NOT NULL ,
"CREATED_USER_NAME" VARCHAR2(55 CHAR) NOT NULL ,
"DIS_PLAY_ORDER_BY" NUMBER(10) NULL ,
"IS_SHOW" NUMBER(10) NOT NULL ,
"LAST_UPDATE_DATE_TIME" TIMESTAMP(6)  NOT NULL ,
"LAST_UPDATE_USER_ID" NUMBER(10) NOT NULL ,
"LAST_UPDATE_USER_NAME" VARCHAR2(255 CHAR) NOT NULL ,
"NAME" VARCHAR2(255 CHAR) NOT NULL ,
"PARENT_ID" NUMBER(10) NOT NULL ,
"DESCRIPTION" VARCHAR2(255 CHAR) NULL ,
"HAS_CHILD" NUMBER(1) NULL ,
"ENAME" VARCHAR2(255 CHAR) NULL ,
"ICON" VARCHAR2(255 CHAR) NULL ,
"PATH" VARCHAR2(255 CHAR) NULL ,
"E_NAME" VARCHAR2(255 CHAR) NULL ,
"AMPUTATED" NUMBER(10) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of MENU
-- ----------------------------
INSERT INTO "PERSONPAPER"."MENU" VALUES ('342', 'M_PERSONNEL_SYSTEMSETTINGS_USERMANAGEMENT', TO_TIMESTAMP(' 2019-06-27 11:41:33:705000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '200', '0', TO_TIMESTAMP(' 2019-06-27 11:41:33:705000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '用户管理', '341', null, '0', null, 'user', 'index/system/user', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('228', 'M_PERSONNEL_ADDRESSBOOKMANAGEMENT', TO_TIMESTAMP(' 2018-12-17 09:58:35:011000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '3000', '1', TO_TIMESTAMP(' 2019-02-18 10:42:23:250000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '通讯录管理', '35', null, '0', null, 'home', 'index/address', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('35', 'M_PERSONNEL_PERSONNEL', TO_TIMESTAMP(' 2018-10-05 14:56:06:895000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '0', '0', TO_TIMESTAMP(' 2019-06-27 11:38:31:035000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '人力资源管理系统', '0', 'string', '1', null, null, null, null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('43', 'M_PERSONNEL_ORGANIZATION', TO_TIMESTAMP(' 2018-10-05 15:04:02:662000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '1000', '0', TO_TIMESTAMP(' 2018-11-12 10:32:34:832000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '组织机构管理', '35', 'string', '0', null, 'home', 'index/org', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('44', 'M_PERSONNEL_EMPLOYEES', TO_TIMESTAMP(' 2018-10-05 15:04:23:446000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '2000', '0', TO_TIMESTAMP(' 2019-01-08 14:25:13:254000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '人员管理', '35', 'string', '0', null, 'user', 'index/staff', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('46', 'M_PERSONNEL_JOBS', TO_TIMESTAMP(' 2018-10-05 15:05:10:596000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '4000', '0', TO_TIMESTAMP(' 2018-11-12 10:34:16:504000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '职务管理', '35', 'string', '0', null, 'solution', 'index/job', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('47', 'M_PERSONNEL_JOBCHANGE', TO_TIMESTAMP(' 2018-10-05 15:05:29:915000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '6000', '0', TO_TIMESTAMP(' 2019-01-08 14:17:41:848000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '人员岗位变动', '35', 'string', '0', null, 'team', 'index/jobChange', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('48', 'M_ATTENDANCE_ATTENDANCEMANAGEMENT_ATTENDANCERULE', TO_TIMESTAMP(' 2018-10-05 15:06:34:446000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', 'admin', '200', '1', TO_TIMESTAMP(' 2019-03-26 08:56:15:804000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '考勤规则设置', '124', 'string', '0', null, 'safety', 'index/attendance/rule', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('341', 'M_PERSONNEL_SYSTEMSETTINGS_SYSTEMSETTINGS', TO_TIMESTAMP(' 2019-06-27 11:38:31:049000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '7000', '0', TO_TIMESTAMP(' 2019-06-27 11:43:45:812000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '系统设置', '35', null, '1', null, 'setting', null, null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('343', 'M_PERSONNEL_SYSTEMSETTINGS_ROLEMANAGEMENT', TO_TIMESTAMP(' 2019-06-27 11:42:49:565000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '300', '0', TO_TIMESTAMP(' 2019-06-27 11:42:49:565000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '角色管理', '341', null, '0', null, 'tag-o', 'index/system/role', null, null);
INSERT INTO "PERSONPAPER"."MENU" VALUES ('344', 'M_PERSONNEL_SYSTEMSETTINGS_MENU', TO_TIMESTAMP(' 2019-06-27 11:43:45:818000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '600', '0', TO_TIMESTAMP(' 2019-06-27 11:50:40:048000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '菜单管理', '341', null, '0', null, 'user', 'index/system/menu', null, null);

-- ----------------------------
-- Checks structure for table MENU
-- ----------------------------
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CODE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("IS_SHOW" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("PARENT_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CODE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("IS_SHOW" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("PARENT_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CODE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("IS_SHOW" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("PARENT_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CODE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("IS_SHOW" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("PARENT_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CODE" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("IS_SHOW" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."MENU" ADD CHECK ("PARENT_ID" IS NOT NULL);
