/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : local
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : PERSONPAPER

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-07-17 17:50:42
*/


-- ----------------------------
-- Table structure for ROLE
-- ----------------------------
DROP TABLE "PERSONPAPER"."ROLE";
CREATE TABLE "PERSONPAPER"."ROLE" (
"ID" NUMBER(10) NOT NULL ,
"CREATED_DATE_TIME" TIMESTAMP(6)  NOT NULL ,
"CREATED_USER_ID" NUMBER(10) NOT NULL ,
"CREATED_USER_NAME" VARCHAR2(55 CHAR) NOT NULL ,
"DESCRIPTION" VARCHAR2(255 CHAR) NULL ,
"LAST_UPDATE_DATE_TIME" TIMESTAMP(6)  NOT NULL ,
"LAST_UPDATE_USER_ID" NUMBER(10) NOT NULL ,
"LAST_UPDATE_USER_NAME" VARCHAR2(255 CHAR) NOT NULL ,
"NAME" VARCHAR2(255 CHAR) NOT NULL ,
"DEFAULT_PERMISSIONS" NUMBER(10) NULL ,
"AMPUTATED" NUMBER(10) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ROLE
-- ----------------------------
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('342', TO_TIMESTAMP(' 2019-06-28 10:15:14:466000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', null, TO_TIMESTAMP(' 2019-06-28 10:23:00:978000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '一般员工', '0', null);
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('343', TO_TIMESTAMP(' 2019-06-28 11:34:43:701000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', null, TO_TIMESTAMP(' 2019-06-28 11:34:43:701000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1096', '中心机关', '部门账号', '1', null);
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('202', TO_TIMESTAMP(' 2019-02-13 16:04:32:036000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1102', '公共资源交易中心', null, TO_TIMESTAMP(' 2019-02-13 16:04:32:036000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1102', '公共资源交易中心', '公共资源交易中心专用角色', '0', null);
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('124', TO_TIMESTAMP(' 2019-01-19 13:53:17:410000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1372', '00060', null, TO_TIMESTAMP(' 2019-01-19 13:53:17:410000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1372', '00060', '业务一科角色', '0', null);
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('242', TO_TIMESTAMP(' 2019-03-11 09:29:43:521000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1173', '新登分中心窗口', null, TO_TIMESTAMP(' 2019-03-11 09:29:43:521000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1173', '新登分中心窗口', '新登窗口角色', '0', null);
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('190', TO_TIMESTAMP(' 2019-02-02 13:42:33:883000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1378', '中心窗口', null, TO_TIMESTAMP(' 2019-02-02 14:32:42:367000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1378', '中心窗口', '部门账号', '0', null);
INSERT INTO "PERSONPAPER"."ROLE" VALUES ('244', TO_TIMESTAMP(' 2019-03-13 15:04:04:036000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1153', '场口分中心窗口', null, TO_TIMESTAMP(' 2019-03-13 15:04:04:036000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1153', '场口分中心窗口', '场口窗口角色', '0', null);

-- ----------------------------
-- Checks structure for table ROLE
-- ----------------------------
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."ROLE" ADD CHECK ("NAME" IS NOT NULL);
