/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : local
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : PERSONPAPER

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-07-17 17:51:34
*/


-- ----------------------------
-- Table structure for WINDOW
-- ----------------------------
DROP TABLE "PERSONPAPER"."WINDOW";
CREATE TABLE "PERSONPAPER"."WINDOW" (
"ID" NUMBER(10) NOT NULL ,
"CREATED_DATE_TIME" TIMESTAMP(6)  NOT NULL ,
"CREATED_USER_ID" NUMBER(10) NOT NULL ,
"CREATED_USER_NAME" VARCHAR2(55 CHAR) NOT NULL ,
"DESCRIPTION" VARCHAR2(255 CHAR) NULL ,
"LAST_UPDATE_DATE_TIME" TIMESTAMP(6)  NOT NULL ,
"LAST_UPDATE_USER_ID" NUMBER(10) NOT NULL ,
"LAST_UPDATE_USER_NAME" VARCHAR2(55 CHAR) NOT NULL ,
"NAME" VARCHAR2(55 CHAR) NOT NULL ,
"ORGANIZATION_ID" NUMBER(10) NOT NULL ,
"USER_ID" NUMBER(10) NULL ,
"WINDOW_IP" VARCHAR2(15 CHAR) NULL ,
"WINDOW_NO" VARCHAR2(55 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of WINDOW
-- ----------------------------

-- ----------------------------
-- Indexes structure for table WINDOW
-- ----------------------------

-- ----------------------------
-- Checks structure for table WINDOW
-- ----------------------------
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("CREATED_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("CREATED_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("CREATED_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("LAST_UPDATE_DATE_TIME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("LAST_UPDATE_USER_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("LAST_UPDATE_USER_NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("ORGANIZATION_ID" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK ("WINDOW_NO" IS NOT NULL);
ALTER TABLE "PERSONPAPER"."WINDOW" ADD CHECK (organization_id>=1 AND organization_id<=99999999);

-- ----------------------------
-- Primary Key structure for table WINDOW
-- ----------------------------
ALTER TABLE "PERSONPAPER"."WINDOW" ADD PRIMARY KEY ("ID");
